# Indica la versión exacta que usas
sonar.python.version=3.13
# Excluye archivos que no son código fuente o que causan conflictos
sonar.exclusions=backend/test_summary.txt, **/*.log, **/*.tmp

sonar.python.coverage.reportPaths=coverage.xml
# Si tu proyecto soporta múltiples versiones, sepáralas por coma
# sonar.python.version=3.9, 3.10, 3.11
